//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace E_Learning.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class Course_Chapter
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Course_Chapter()
        {
            this.Course_Chapter_Content = new HashSet<Course_Chapter_Content>();
        }
    
        public int id { get; set; }
        public Nullable<int> course_id { get; set; }
        public string chapter_title { get; set; }
        public Nullable<int> num_of_video { get; set; }
        public Nullable<int> num_of_assignment { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Course_Chapter_Content> Course_Chapter_Content { get; set; }
    }
}
