//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace E_Learning.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class Course
    {
        public int id { get; set; }
        public string course_title { get; set; }
        public string course_brief { get; set; }
        public Nullable<int> tutor_id { get; set; }
        public Nullable<decimal> course_fee { get; set; }
        public Nullable<int> language_id { get; set; }
    
        public virtual Language Language { get; set; }
        public virtual Teacher Teacher { get; set; }
    }
}
