//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace E_Learning.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class Course_Chapter_Content
    {
        public int id { get; set; }
        public Nullable<int> course_chapter_id { get; set; }
        public Nullable<int> content_type_id { get; set; }
        public string content_name { get; set; }
        public string content_link { get; set; }
        public Nullable<decimal> time_required_in_hour { get; set; }
    
        public virtual Content_Type Content_Type { get; set; }
        public virtual Course_Chapter Course_Chapter { get; set; }
    }
}
