//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace E_Learning.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class Learning_Progress
    {
        public int id { get; set; }
        public Nullable<int> entrollment_id { get; set; }
        public Nullable<int> course_chapter_content_id { get; set; }
        public string begin_timestamp { get; set; }
        public string status { get; set; }
    
        public virtual Enrollment Enrollment { get; set; }
    }
}
