//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace E_Learning.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class Student_Feedback
    {
        public int id { get; set; }
        public Nullable<int> feedback_id { get; set; }
        public Nullable<int> student_id { get; set; }
    
        public virtual Feedback Feedback { get; set; }
        public virtual Student Student { get; set; }
    }
}
