//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace E_Learning.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class Teacher_Student_Email
    {
        public int id { get; set; }
        public Nullable<int> teacher_email_id { get; set; }
        public Nullable<int> student_email_id { get; set; }
        public Nullable<int> admin_email_id { get; set; }
    
        public virtual Student_Email Student_Email { get; set; }
        public virtual Teacher_Email Teacher_Email { get; set; }
        public virtual Admin_Email Admin_Email { get; set; }
    }
}
